name: Release

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    build:
        name: Build and Release
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - goos: linux
                      goarch: amd64
                      output: linux-x86_64
                    - goos: linux
                      goarch: arm64
                      output: linux-arm64
                    - goos: darwin
                      goarch: amd64
                      output: darwin-x86_64
                    - goos: darwin
                      goarch: arm64
                      output: darwin-arm64
                    - goos: windows
                      goarch: amd64
                      output: windows-x86_64.exe
                    - goos: windows
                      goarch: arm64
                      output: windows-arm64.exe

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24"

            - name: Build binary
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
              run: |
                  VERSION=${{ github.ref_name }}
                  FILENAME=${{ matrix.output }}
                  if [[ "$FILENAME" == *.exe ]]; then
                    PLATFORM_ARCH="${FILENAME%.exe}"
                    VERSIONED_FILENAME="termodoro-${VERSION}-${PLATFORM_ARCH}.exe"
                  else
                    PLATFORM_ARCH="$FILENAME"
                    VERSIONED_FILENAME="termodoro-${VERSION}-${PLATFORM_ARCH}"
                  fi
                  go build -ldflags="-s -w -X main.version=${VERSION}" -o ./bin/${VERSIONED_FILENAME} .
                  chmod +x ./bin/${VERSIONED_FILENAME}

            - name: Upload Release Asset
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  VERSION=${{ github.ref_name }}
                  FILENAME=${{ matrix.output }}
                  if [[ "$FILENAME" == *.exe ]]; then
                    PLATFORM_ARCH="${FILENAME%.exe}"
                    VERSIONED_FILENAME="termodoro-${VERSION}-${PLATFORM_ARCH}.exe"
                  else
                    PLATFORM_ARCH="$FILENAME"
                    VERSIONED_FILENAME="termodoro-${VERSION}-${PLATFORM_ARCH}"
                  fi
                  gh release upload ${{ github.ref_name }} ./bin/${VERSIONED_FILENAME} --clobber
